language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0.29
  - 7.1.18
  - 7.2
  - nightly
  - hhvm

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=3.2.*
  - SYMFONY_VERSION=3.3.*
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=4.0.*
  - SYMFONY_VERSION=4.1.*
  - DEPENDENCIES="beta"

matrix:
  fast_finish: true
  exclude:
    - php: 7.0.29
      env: SYMFONY_VERSION=4.0.*
    - php: 7.0.29
      env: SYMFONY_VERSION=4.1.*
    - php: 7.0.29
      env: DEPENDENCIES=beta
    - php: 7.1.18
      env: SYMFONY_VERSION=3.2.*
    - php: 7.1.18
      env: SYMFONY_VERSION=3.3.*
    - php: 7.1.18
      env: DEPENDENCIES=beta
    - php: nightly
      env: SYMFONY_VERSION=3.2.*
    - php: nightly
      env: SYMFONY_VERSION=3.3.*
    - php: nightly
      env: DEPENDENCIES=beta
  allow_failures:
    - php: nightly
    - php: hhvm
    - env: DEPENDENCIES="beta"

before_install:
  - composer install --no-interaction
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - mkdir -p build/logs

install:
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi

script:
  - composer validate-files
  - composer check-code-style
  - composer check-security
  - composer run-tests-with-clover

after_script:
  - php bin/coveralls -v
