language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
      env: SYMFONY_VERSION=3.2.*
    - php: 7.0
      env: SYMFONY_VERSION=3.3.*
    - php: 7.0
      env: DEPENDENCIES=beta
    - php: 7.1
      env: SYMFONY_VERSION=3.2.*
    - php: 7.1
      env: SYMFONY_VERSION=3.3.*
    - php: 7.1
      env: DEPENDENCIES=beta
    - php: nightly
      env: SYMFONY_VERSION=3.2.*
    - php: nightly
      env: SYMFONY_VERSION=3.3.*
    - php: nightly
      env: DEPENDENCIES=beta
  allow_failures:
    - php: nightly

env:
  global:
    - deps=no

before_install:
  - composer self-update
  # Set composer minimum-stability configuration filter to beta versions
  - if [ "$DEPENDENCIES" = "beta" ]; then perl -pi -e 's/^}$/,"minimum-stability":"beta"}/' composer.json; fi;

install:
  - if [ "$deps" = "no" ]; then composer update; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;

script:
  - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml

after_script:
  - php ./vendor/bin/coveralls -v
