language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly

env:
  global:
    - deps=no

before_install:
  - composer self-update

install:
  - if [ "$deps" = "no" ]; then composer update; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;

script:
  - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml
